name: tianyan
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter /Users/zerowolf/software/flutter/.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.32.3/lib

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: "^0.1.6"
  dio: ^0.0.10
  scoped_model: "^0.2.0"
  chewie: "^0.6.1"
  image_picker: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
   uses-material-design: true

  # To add assets to your application, add an assets section, like this:
   assets:
    - asset/images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have
  #  # "family" key with the font family name, and a "fonts" key with aa
  # list giving the asset and other descriptors for the font. For
  # example:

   fonts:
     - family: PingFang TC
       fonts:
         - asset: asset/fonts/PingFang.ttf
           weight: 700

     - family: Lobster
       fonts:
           - asset: asset/fonts/Lobster-1.4.otf

     - family: FZLanTing
       fonts:
         - asset: asset/fonts/FZLanTingHeiS-DB1-GB-Regular.TTF
           weight: 200
#
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
